name: Fuck you
favicon: null
layout_spectrum: 0.3090946418233216
typography_spectrum: 0.018082757480442524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4924504638183862
  lightness: 0.4872418297454715
  saturation: 0.26173919602297246
  rhythmicContrast: 0.8013935703784227
purpose: []
